{% set version = "4.2.0" %}

package:
  name: libpysal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/libpysal/libpysal-{{ version }}.tar.gz
  sha256: a14469e9f307308f19a3c27b76647d04254e3ca77cdbbefce31426d759d6e50f

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy >=1.3
    - pandas
    - scipy >=0.11

test:
  imports:
    - libpysal
    - libpysal.cg
    - libpysal.cg.ops
    - libpysal.examples
    - libpysal.examples.examples
    - libpysal.io
    - libpysal.io.geotable
    - libpysal.io.util
    - libpysal.weights

about:
  home: http://pysal.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Core components of PySAL A library of spatial analysis functions

extra:
  recipe-maintainers:
    - ocefpaf
