{% set version = "4.0.0" %}

package:
  name: libpysal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/libpysal/libpysal-{{ version }}.tar.gz
  sha256: f865dd3dc54596bc8960569db6719dc52b854188b4862ed075a08df8a22d7aaa

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy >=1.3
    - pandas
    - scipy >=0.11

test:
  imports:
    - libpysal
    - libpysal.cg
    - libpysal.cg.ops
    - libpysal.cg.ops.tests
    - libpysal.cg.tests
    - libpysal.examples
    - libpysal.examples.examples
    - libpysal.examples.tests
    - libpysal.io
    - libpysal.io.IOHandlers
    - libpysal.io.IOHandlers.tests
    - libpysal.io.geotable
    - libpysal.io.geotable.tests
    - libpysal.io.tests
    - libpysal.io.util
    - libpysal.io.util.tests
    - libpysal.weights
    - libpysal.weights.tests

about:
  home: http://pysal.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Core components of PySAL A library of spatial analysis functions

extra:
  recipe-maintainers:
    - ocefpaf
