{% set version = "4.10" %}

package:
  name: libpysal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/libpysal/libpysal-{{ version }}.tar.gz
  sha256: 4d3127802c7c06289ffb211d10202dd8d14b10039a81249920769ce4b987e3b5
build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<310 or s390x]

requirements:
  host:
    - python
    - pip
    - pytest-runner
    - setuptools
    - wheel
  run:
    - python
    - beautifulsoup4 >=4.10
    - scipy >=1.8
    - numpy >=1.22
    - pandas >=1.4
    - packaging >=22
    - platformdirs >=2.0.2
    - requests >=2.27
    - shapely >=2.0.1
    - scikit-learn >=1.1
    - geopandas >=0.10.0

test:
  imports:
    - libpysal
    - libpysal.cg
    - libpysal.cg.ops
    - libpysal.examples
    - libpysal.io
    - libpysal.io.geotable
    - libpysal.io.iohandlers
    - libpysal.io.tests
    - libpysal.io.util
    - libpysal.weights
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pysal.org
  summary: Core components of PySAL A library of spatial analysis functions
  description: |
    libpysal offers four modules that form the building blocks in many upstream 
    packages in the PySAL family. Spatial Weights: libpysal.weights. Input-and 
    output: libpysal.io. Computational geometry: libpysal.cg. Built-in example 
    datasets libpysal.examples
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/pysal/libpysal
  doc_url: https://pysal.org/libpysal/

extra:
  recipe-maintainers:
    - ocefpaf
