{% set version = "4.3.0" %}

package:
  name: libpysal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/l/libpysal/libpysal-{{ version }}.tar.gz
  sha256: d7cb34aa20f07c93d8f1f12431aa7c6aa9a08b92cc4396022a04fc2086e5d2d7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - scipy >=0.11
    - numpy >=1.3
    - pandas
    - requests
    - jinja2
    # not in the metadata but need
    - bs4

test:
  imports:
    - libpysal
    - libpysal.cg
    - libpysal.cg.ops
    - libpysal.examples
    - libpysal.io
    - libpysal.io.geotable
    - libpysal.io.iohandlers
    - libpysal.io.tests
    - libpysal.io.util
    - libpysal.weights
# pip check is not smart enough to know that an import name is not the package name :-(
# commands:
#  - pip check
# requires:
#  - pip

about:
  home: http://pysal.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Core components of PySAL A library of spatial analysis functions

extra:
  recipe-maintainers:
    - ocefpaf
