travis:
  secure:
    BINSTAR_TOKEN: IsOUwbWe5jwWkD5c2nf0wwhjBa4TOIbOKNDRH11zrrw+8LhWMg6M04ssCBZh1vXt8cBEmAjS7XIYu8lNYOUNYPObx+dTYpDSbgvX/AwbyMmF9DjJr3jWR90rrjoF/wavpf4TgP1KVx9W2r9ZV0/vIEWeDqD3uPqy8O7KqWnqAUD2hMLI5WnxkkolYUpzAk+jcj9VCRnG3GHM9HJyzcNMGC3C0GgPhpliArCAq8hj6S4UyTolAEixNxCJhk1bP9DF6fLFZ692kS51oFBAhPJ9QBCmMET+KbK6lK47DKNPrn3XKEf7mGKP+qq2d0O3kgWPvgSflf3TUNq0yb2mFrK7HGsgR4UL2FtkJ+fd5ffzE26idAj11TQRXnFYUHmuD6L1xnb92grOy+6bk6Q6XiL/9/GvYcXQxeKEObJ1DRYb9Du2IVPN8vzKrYG3yjLzgk0+STxKZ9wMAQRYjzyAQkL6NP9WQCyiBaFqwU8CVcAUoJZZwLHBvGb8QOuVJeTjGCaa2CeO9ZqzLK7kvCDvwOJT8vkEfm4R8ReK62UlRLsQhoXwJBPrgFGEqC8OmgWlfZAXsygn24wVjIpf16D3GHuu3Pi1Uz2NlK/infhKiD8gdG5BDr3b3pGc9Idoy9pzmm6WvrtbE/gvbqTb7kUn9PXT04N3CzhP4qA/K4/6LIWBhdQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
